name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: ASCII-UML-Generator
      run: cd ASCII-UML-Generator && cmake -B build -DCMAKE_BUILD_TYPE=Debug && cmake --build build --parallel 20 && ctest --test-dir build
    - name: allocCatcher
      run: cd allocCatcher && cmake -B build -DCMAKE_BUILD_TYPE=Debug && cmake --build build --parallel 20 && ctest --test-dir build
    - name: almost_always_lockfree
      run: cd almost_always_lockfree && cmake -B build -DCMAKE_BUILD_TYPE=Debug && cmake --build build --parallel 20 && ctest --test-dir build
    - name: conceptsInterfaces
      run: cd conceptsInterfaces && cmake -B build -DCMAKE_BUILD_TYPE=Debug && cmake --build build --parallel 20 && ctest --test-dir build
    - name: cudp
      run: cd cudp && cmake -B build -DCMAKE_BUILD_TYPE=Debug && cmake --build build --parallel 20 && ctest --test-dir build
    - name: doubly_mapped_lockfree_queue_build
      run: cd doubly_mapped_lockfree_queue && cmake -B build -DCMAKE_BUILD_TYPE=Debug && cmake --build build --parallel 20 && ctest --test-dir build
    - name: exshelf
      run: cd exshelf && cmake -B build -DCMAKE_BUILD_TYPE=Debug && cmake --build build --parallel 20 && ctest --test-dir build
    - name: neural_network_physics_build
      run: cd neural_network_physics && cmake -B build -DCMAKE_BUILD_TYPE=Debug && cmake --build build --parallel 20 && ctest --test-dir build
    - name: qtHelloWorld
      run: cd qtHelloWorld && cmake -B build -DCMAKE_BUILD_TYPE=Debug && cmake --build build --parallel 20 && ctest --test-dir build
    - name: simple_parser
      run: cd simple_parser && cmake -B build -DCMAKE_BUILD_TYPE=Debug && cmake --build build --parallel 20 && ctest --test-dir build
    - name: simple_thread_pool
      run: cd simple_thread_pool && cmake -B build -DCMAKE_BUILD_TYPE=Debug && cmake --build build --parallel 20 && ctest --test-dir build
