name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: doubly_mapped_lockfree_queue_build
      run: cd doubly_mapped_lockfree_queue && cmake -B build -DCMAKE_BUILD_TYPE=Debug
    - name: doubly_mapped_lockfree_queue_test
      run: ctest --test-dir build
